[build]
  functions = "netlify/functions"  # This tells Netlify where to find your serverless functions

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
